"""Add chat conversation and message tables

Revision ID: 4299daa1a2ef
Revises: c33e7b7aa368
Create Date: 2026-08-04 00:36:14.498925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4299daa1a2ef'
down_revision: Union[str, Sequence[str], None] = 'c33e7b7aa368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
